---
- name: Create directories
  file: path={{ item }} state=directory owner=root group=wheel mode=0755
  with_items:
    - /var/www/htdocs/preseed
    - /srv
    - /srv/tftpboot

- name: Configure httpd
  copy: src=httpd.conf dest=/etc/httpd.conf owner=root group=wheel mode=0644
  notify:
    - httpd

- name: Enable httpd
  lineinfile: dest=/etc/rc.conf.local.d/httpd line='httpd_flags=""' owner=root group=wheel mode=0644 create=yes
  notify:
    - rc.conf.local
    - httpd

- name: Configure and Enable tftpd
  lineinfile: dest=/etc/rc.conf.local.d/tftpd line='tftpd_flags="/srv/tftpboot"' owner=root group=wheel mode=0644 create=yes
  notify:
    - rc.conf.local
    - tftpd
